version: '3.1'
services:
  stats-service:
    build: ./stats-service/stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats

  stats-db:
    image: postgres:14.10
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats
      - PGUSER=stats
      - POSTGRES_PASSWORD=stats

  ewm-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=explore
      - POSTGRES_USER=explore
      - PGUSER=explore
      - POSTGRES_PASSWORD=explore

  ewm-service:
    build: ./ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explore
      - SPRING_DATASOURCE_USERNAME=explore
      - SPRING_DATASOURCE_PASSWORD=explore